endpoint rejestracji
wojbog/praktyki_backend pull request #5
Opened 2021-05-06 11:20 UTC by wojbog

dodanie ednpoint,walidacja danych,połączenie z bazą danych

2021-05-06 11:24 UTC, shhhQuiettt commented on server.go
>  	app.Listen(":3000")
Zmień na 3001 w końcu

2021-05-06 11:47 UTC, shhhQuiettt commented on serviceDB/serviceDB.go
> +	if errv:=baza.DB.Collection("zadania").FindOne(context.Background(), bson.M{"email":user.Email}); errv !=nil {
Chyba w "users"

2021-05-06 11:50 UTC, shhhQuiettt commented on serviceDB/serviceDB.go
> +	if errv:=baza.DB.Collection("zadania").FindOne(context.Background(), bson.M{"email":user.Email}); errv !=nil {
Chyba nie pusty context.Background() tylko ten z bazy

2021-05-06 12:09 UTC, akruszewski commented on server.go
>  	app.Listen(":3000")
Ta wartosc powinna isc z enva.

2021-05-06 12:15 UTC, akruszewski requested changes

2021-05-06 12:15 UTC, akruszewski commented on baza/baza.go
> +	client, err := mongo.NewClient(options.Client().ApplyURI("mongodb://127.0.0.1:27017"))
Ten url powinien isc z enva.

2021-05-06 12:15 UTC, akruszewski commented on server.go
> +	app.Post("/newUser",user.SetUser)//endpoint dodawania uzytkownika do bazy
Najlepiej `createUser`, albo `registerUser`.

2021-05-06 12:15 UTC, akruszewski commented on serviceDB/serviceDB.go
> +	if errv:=baza.DB.Collection("zadania").FindOne(context.Background(), bson.M{"email":user.Email}); errv !=nil {
ctx powinien zostac przekazany do funkcji jako pierwszy parametr. Poczytaj: https://golang.org/pkg/context/

2021-05-06 12:15 UTC, akruszewski commented on serviceDB/serviceDB.go
> +		return errors.New("konto istnieje")
cala komunikacja backendu najlepiej po angielsku, ewentualnie message bylyby tlumaczone na froncie.

2021-05-06 12:15 UTC, akruszewski commented on user/user.go
> +	fmt.Println("jestem")
Do PR nie wypychamy komentow ktore nie powinny sie znalezc w produkcyjnym kodzie.

2021-05-06 12:15 UTC, akruszewski commented on user/user.go
> +	fmt.Println(p.Name)
Do PR nie wypychamy komentow ktore nie powinny sie znalezc w produkcyjnym kodzie.

2021-05-06 12:17 UTC, akruszewski commented
Logowanie najlepiej ogarnij z logrus. wszystkie errory powinny byc logowane, dobrze tez logowac warningi i info.

2021-05-07 13:11 UTC, akruszewski requested changes
Juz jest prawie ok, ale te rzeczy z enva powinny byc sprawdzone czy istnieja, i jezeli nie, to powinna zostac podjeta jakas akcja: ustawienie wartosci defaultowej, albo np. zwrocenie bledu, jezeli zmienna musi byc ustawiona.

2021-05-07 13:11 UTC, akruszewski commented on baza/baza.go
> +	client, err := mongo.NewClient(options.Client().ApplyURI(os.Getenv("URL_BAZA")))
wyglada git, ale najlepiej nazwij to MONGO_URL

2021-05-07 13:11 UTC, akruszewski commented on baza/baza.go
> +	DB = *client.Database("praktyki")
to tez dalbym do enva jako MONGO_DB, i jezeli nie ma takiej zmiennej, to ustawilbym default, np. "praktyki", ale moze lepiej nazwe aplikacji, czy cos w ten desen.

2021-05-07 13:11 UTC, akruszewski commented on server.go
>  		return c.SendString("Hello, World!")
Tego bym sie pozbyl.

2021-05-07 13:11 UTC, akruszewski commented on user/user.go
> +	log.Info("success")
Malo informatywny ten log. Jaka akcja skonczyla sie z sukcesem? Jaki np. user id zostal dodany, itp.

2021-05-10 08:23 UTC, akruszewski requested changes

2021-05-10 08:23 UTC, akruszewski commented on baza/baza.go
> +var DB mongo.Database
Globalne zmienne to na prawde zly pomysl, wszystko powinno byc przekazywane przez funkcje, i, jezeli istnieje taka potrzeba, trzymane w struktorach. Problem z globalsami jest taki, ze bardzo latwo mozesz miec errory z dostepami, jezeli dwie metody beda probowaly sie dostac do tego samego miejsca w pamieci.

2021-05-10 08:23 UTC, akruszewski commented on baza/baza.go
> +	connectToMongo()
Jak w komentarzu wyzej, init polaczenia do mongo to nienajlepsza idea.

2021-05-10 08:23 UTC, akruszewski commented on person/person_test.go
> +func TestVlidatePasswordFalse(t *testing.T) {
Literowka, powinno byc Validate

2021-05-10 08:23 UTC, akruszewski commented on person/person_test.go
> +func TestVlidatePasswordFalse(t *testing.T) {
I w zasadzie to cos w desen TestValidatePasswordReturnFalseIfPasswordIsInvalid

2021-05-10 08:23 UTC, akruszewski commented on person/person_test.go
> +func TestVlidatePasswordFalse(t *testing.T) {
Tyczy sie to wszystkich testow.

2021-05-10 08:23 UTC, akruszewski commented on server.go
>  		return c.SendString("Hello, World!")
Ponawiam request o zmiane.

2021-05-10 08:23 UTC, akruszewski commented on serviceDB/serviceDB.go
> +package serviceDB
proponuje repository/user/user.go, komunikacja z baza najlepiej zeby lezala w repositories, a logika biznesowa w services, handlery http w handlers, a routing w server.

2021-05-11 07:22 UTC, akruszewski requested changes

2021-05-11 07:22 UTC, akruszewski commented on handlers/createUser.go
> +func CreateUser(c *fiber.Ctx) error {//dodawanie użytkownika do bazy
Komentarze po angielsku poprosze, i nie tak dokumentuje sie funkcje: https://blog.golang.org/godoc

2021-05-11 07:22 UTC, akruszewski commented on repository/user/user.go
> +type Baza struct {
Repository

2021-05-12 06:21 UTC, akruszewski requested changes

2021-05-12 06:21 UTC, akruszewski commented on service/person.go
> +func (p *Person) Validation() ([]string, error) {//walidacja struktury użytkownika
Nazwalbym to Validate, bo to akcja, Validation bardziej by sie nadawalo do np. tworzenia obiektu Validation.

2021-05-12 06:21 UTC, akruszewski commented on handlers/createUser.go
> +	if str,err:=col.InsertUser(c.Context(),p);err!=nil {//dodawanie do bazy
to i walidacja powinna byc w serwisie, nie w handlerze, i serwis uzyty tutaj.

2021-05-12 08:58 UTC, akruszewski requested changes

2021-05-12 08:58 UTC, akruszewski commented on handlers/createUser.go
> +			"error":   err.Error()})
Do uzytkownika nie chcesz wysylac errora ktory zucila aplikacja w tym przypadku, to nie bedzie mowilo zwyklemu uzytkownikowi + to moze bys security issue. Tutaj lepiej wyswietlic customowy error: "Cannot read request", czy cos w ten desen.

2021-05-12 08:58 UTC, akruszewski commented on handlers/createUser.go
> +		return c.Status(400).JSON(&fiber.Map{
Tutaj robisz zalozenie, ze dostaniesz tylko validation error. Trzeba by rozroznic validation errory od nieoczekiwanych errorow, tj. 500.

2021-05-12 12:52 UTC, akruszewski approved these changes

2021-05-12 12:57 UTC, merged